spring:
  profiles:
    active: h2  # 기본 프로파일 설정: H2
  data:
    redis:
      host: localhost
      port: 6379

# H2 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # Redis 설정 추가
  data:
    redis:
      host: localhost
      port: 6379

# 테스트 프로파일 설정 (임베디드 Redis용)
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379

# MySQL 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://192.168.219.101:3306/zbproject01?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 6188
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
